// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhXorXIzv63Y-CXRWFDfJdp3jZvqZRqJA',
    appId: '1:287256212010:web:a1f14c28b11a8aefed4953',
    messagingSenderId: '287256212010',
    projectId: 'wishpr-1857a',
    authDomain: 'wishpr-1857a.firebaseapp.com',
    storageBucket: 'wishpr-1857a.firebasestorage.app',
    measurementId: 'G-H2BC2JG9R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKz4DSXz-oenC_Y3aBa2VQSpIPnlEYqIA',
    appId: '1:287256212010:android:97cdabf70012d77aed4953',
    messagingSenderId: '287256212010',
    projectId: 'wishpr-1857a',
    storageBucket: 'wishpr-1857a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRY8u4gQiLgj7PAxDg2jxirA9krBFL1U4',
    appId: '1:287256212010:ios:bdd67c304e7b3a9aed4953',
    messagingSenderId: '287256212010',
    projectId: 'wishpr-1857a',
    storageBucket: 'wishpr-1857a.firebasestorage.app',
    iosBundleId: 'com.example.wishprApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRY8u4gQiLgj7PAxDg2jxirA9krBFL1U4',
    appId: '1:287256212010:ios:bdd67c304e7b3a9aed4953',
    messagingSenderId: '287256212010',
    projectId: 'wishpr-1857a',
    storageBucket: 'wishpr-1857a.firebasestorage.app',
    iosBundleId: 'com.example.wishprApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhXorXIzv63Y-CXRWFDfJdp3jZvqZRqJA',
    appId: '1:287256212010:web:3db0b27857c7ad54ed4953',
    messagingSenderId: '287256212010',
    projectId: 'wishpr-1857a',
    authDomain: 'wishpr-1857a.firebaseapp.com',
    storageBucket: 'wishpr-1857a.firebasestorage.app',
    measurementId: 'G-G41ED78G1C',
  );
}
